### PR TITLE
feat: Add utils and models

### PR DESCRIPTION
**Pull request by SiddheshKanawade**
Added utils and models to the repository. Also, disabled clippy check to avoid unused variables error. I plan to add license in the final PR. 

Signed-off-by: SiddheshKanawade [siddhesh.kanawade@iitgn.ac.in](mailto:siddhesh.kanawade@iitgn.ac.in)

### CODE REVIEW

**Comment by SiddheshKanawade** [comment]
@hsluoyz @hackerchai please review

**Comment by hsluoyz** [comment]
@SiddheshKanawade I think we should add headers at earlier convenience (in this PR). An open source project is always ongoing and there's no such "final PR" actually.

**Comment by SiddheshKanawade** [comment]
> @SiddheshKanawade I think we should add headers at earlier convenience (in this PR). An open source project is always ongoing and there's no such "final PR" actually.

Agree, will do it asap

**Comment by SiddheshKanawade** [comment]
@hsluoyz @hackerchai please check now

**Pull request merged**
